HABITAT = (("Coral", "Coral"), ("HumanVaginalMicroflora", "Human vaginal microflora"),
           ("HypersalineSediment", "Hypersaline sediment"),
           ("BirdsIntestinalMicroflora", "Birds intestinal microflora"), ("PaperMill", "Paper mill"),
           ("RespiratoryTract", "Respiratory tract"), ("Potato", "Potato"), ("Bovine", "Bovine"),
           ("SodaLakes", "Soda lakes"), ("HumanAbscess", "Human abscess"), ("Bioreactor", "Bioreactor"),
           ("Rock", "Rock"), ("DairyIsolates", "Dairy isolates"), ("DeepSea", "Deep sea"), ("Wastewater", "Wastewater"),
           ("Slaughterhouse", "Slaughterhouse"), ("SeaWater", "Sea water"), ("Dog", "Dog"),
           ("DeepSubsurface", "Deep subsurface"), ("SalineWater", "Saline water"),
           ("InsectEndosymbiont", "Insect endosymbiont"), ("Mud", "Mud"), ("Biofilm", "Biofilm"), ("Feces", "Feces"),
           ("Aquifer", "Aquifer"), ("Host", "Host"), ("SulfurSpring", "Sulfur spring"),
           ("AnimalGastrointestinalTract", "Animal gastrointestinal tract"), ("Skin", "Skin"),
           ("AcidMine", "Acid mine"), ("HumanSkin", "Human skin"), ("Sediment", "Sediment"),
           ("Endosymbiont", "Endosymbiont"), ("BiogasReactor", "Biogas reactor"), ("Insect", "Insect"),
           ("SurfaceWater", "Surface water"), ("AnimalFacility", "Animal facility"), ("PlantSurface", "Plant surface"),
           ("SewagePlant", "Sewage plant"), ("Gut", "Gut"), ("NematodeSymbiont", "Nematode symbiont"),
           ("Extreme", "Extreme"), ("Milk", "Milk"), ("MicrobialMat", "Microbial mat"),
           ("ActivatedSludge", "Activated sludge"), ("Hare", "Hare"), ("Sputum", "Sputum"),
           ("HoneyBeeLarva", "Honey bee Larva"), ("Aquaculture", "Aquaculture"), ("OilFields", "Oil fields"),
           ("Human", "Human"), ("Ponds", "Ponds"), ("RiceRoots", "Rice roots"), ("Arctic", "Arctic"),
           ("SaltMarsh", "Salt marsh"), ("Cattle", "Cattle"), ("Fruits", "Fruits"), ("Sand", "Sand"),
           ("Sludge", "Sludge"), ("FreshWater", "Fresh water"), ("RicePaddies", "Rice paddies"), ("Water", "Water"),
           ("AlkalineWater", "Alkaline water"), ("MangroveSoil", "Mangrove soil"),
           ("HumanOralCavity", "Human oral cavity"), ("Abalone", "Abalone"), ("Groundwater", "Groundwater"),
           ("Wood", "Wood"), ("AnimalFeces", "Animal feces"), ("PermafrostSediment", "Permafrost sediment"),
           ("Marine", "Marine"), ("VolcanicWater", "Volcanic water"),
           ("BovineIntestinalMicroflora", "Bovine intestinal microflora"), ("MouseCecum", "Mouse cecum"),
           ("Rhizosphere", "Rhizosphere"), ("PlantRoot", "Plant root"), ("Sheep", "Sheep"),
           ("Endolithic", "Endolithic"), ("OralCavity", "Oral cavity"), ("Pig", "Pig"), ("Hospital", "Hospital"),
           ("Mat", "Mat"), ("HumanFecal", "Human fecal"), ("Mine", "Mine"), ("Compost", "Compost"),
           ("HumanTrachea", "Human trachea"), ("PondWater", "Pond water"), ("Bird", "Bird"), ("Sponge", "Sponge"),
           ("DesertSoil", "Desert soil"), ("SalineSoil", "Saline soil"), ("Seafloor", "Seafloor"),
           ("FermentedFoodProduct", "Fermented food product"), ("HumanAirways", "Human airways"),
           ("BovineRumen", "Bovine rumen"), ("Plant", "Plant"), ("AcidMineDrainage", "Acid mine drainage"),
           ("Food", "Food"), ("TermiteGut", "Termite gut"), ("Lung", "Lung"), ("Mouse", "Mouse"),
           ("RootNodule", "Root nodule"), ("HumanFeces", "Human feces"), ("Animal", "Animal"), ("Algae", "Algae"),
           ("SwineUpperRespiratoryTract", "Swine upper respiratory tract"),
           ("WastewaterTreatmentPlant", "Wastewater treatment plant"), ("MineWater", "Mine water"),
           ("MeatFoodProduct", "Meat food product"), ("BovineUrogenitalTract", "Bovine urogenital tract"),
           ("MarinePlankton", "Marine plankton"), ("Tunicate", "Tunicate"), ("Submarine", "Submarine"),
           ("Salmon", "Salmon"), ("HumanBlood", "Human blood"), ("SaltMine", "Salt mine"), ("Biofilter", "Biofilter"),
           ("HydrocarbonContaminatedSoil", "Hydrocarbon contaminated soil"),
           ("CellulosicSubstrates", "Cellulosic substrates"),
           ("MolluskGastrointestinalTract", "Mollusk gastrointestinal tract"),
           ("HydrothermalSediment", "Hydrothermal sediment"), ("ForestSoil", "Forest soil"), ("Aquatic", "Aquatic"),
           ("HumanIntestinalMicroflora", "Human intestinal microflora"), ("Permafrost", "Permafrost"),
           ("SeaSand", "Sea sand"), ("Air", "Air"), ("LabCulture", "Lab culture"),
           ("MarineSediment", "Marine sediment"), ("Rumen", "Rumen"), ("Mosquito", "Mosquito"),
           ("BovineRespiratoryTract", "Bovine respiratory tract"), ("GastrointestinalTract", "Gastrointestinal tract"),
           ("Vagina", "Vagina"), ("Fish", "Fish"), ("BrackishWater", "Brackish water"), ("Plants", "Plants"),
           ("Soil", "Soil"), ("PoultryMeatProduct", "Poultry meat product"), ("IntestinalTract", "Intestinal tract"),
           ("Goat", "Goat"), ("GingivalCrevices", "Gingival crevices"), ("Unknown", "Unknown"),
           ("Terrestrial", "Terrestrial"), ("UrogenitalTract", "Urogenital tract"),
           ("MammalianGastrointestinalTract", "Mammalian gastrointestinal tract"), ("PlantSymbiont", "Plant symbiont"),
           ("Lake", "Lake"), ("HotSpring", "Hot spring"))

SAMPLE_BODY_SITE = (
    ("Nose", "Nose"), ("Unknown", "Unknown"), ("Wound", "Wound"), ("UrogenitalTract", "Urogenital tract"),
    ("GastrointestinalTract", "Gastrointestinal tract"), ("Brain", "Brain"), ("Abdomen", "Abdomen"), ("Blood", "Blood"),
    ("Ear", "Ear"), ("Heart", "Heart"), ("Skin", "Skin"), ("Root", "Root"), ("Liver", "Liver"), ("Spleen", "Spleen"),
    ("Eye", "Eye"), ("Lung", "Lung"), ("Oral", "Oral"), ("PlantStem", "Plant-stem"), ("PlantRoot", "Plant-root"),
    ("PlantFlower", "Plant-flower"), ("PlantLeaf", "Plant-leaf"), ("Airways", "Airways"))

SAMPLE_BODY_SUB_SITE = (
    ("Subgingival", "Subgingival"), ("Unknown", "Unknown"), ("Urethra", "Urethra"), ("Throat", "Throat"),
    ("Vaginal", "Vaginal"), ("SupragingivalPlaque", "Supragingival plaque"), ("IlealAnalPouch", "Ileal-anal pouch"),
    ("BuccalMucosa", "Buccal mucosa"), ("SubgingivalPlaque", "Subgingival plaque"), ("Conjunctiva", "Conjunctiva"),
    ("Nasal", "Nasal"), ("LungAspirate", "Lung aspirate"), ("UrinaryTract", "Urinary tract"),
    ("Periodontal", "Periodontal"), ("Colon", "Colon"), ("Cecum", "Cecum"), ("Mouth", "Mouth"), ("Gut", "Gut"),
    ("Nares", "Nares"), ("PleuralCavity", "Pleural cavity"), ("UpperRespiratoryTract", "Upper respiratory tract"),
    ("Teeth", "Teeth"), ("Nasopharynx", "Nasopharynx"), ("LowerLimb", "Lower limb"),
    ("RespiratoryTract", "Respiratory tract"), ("IntestinalTract", "Intestinal tract"),
    ("GingivalCrevices", "Gingival crevices"), ("Rumen", "Rumen"), ("Rectal", "Rectal"),
    ("AscendingColon", "Ascending colon"), ("SigmoidColon", "Sigmoid colon"), ("Bronchus", "Bronchus"))
